version: '3.8'

services:
  sqlserver:
    environment:
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - ./deploy/database/init:/docker-entrypoint-initdb.d

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/ApiGateways/ApiGateway:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5000:8080"
      - "5050:8081"

  authors-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Authors/Authors.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5001:8080"
      - "5051:8081"

  publishers-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Publishers/Publishers.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5002:8080"
      - "5052:8081"

  titles-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Titles/Titles.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5003:8080"
      - "5053:8081"

  sales-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Sales/Sales.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5004:8080"
      - "5054:8081"

  employees-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Employees/Employees.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5005:8080"
      - "5055:8081"

  stores-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Stores/Stores.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5006:8080"
      - "5056:8081"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Identity/Identity.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5007:8080"
      - "5057:8081"

  notifications-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Notifications/Notifications.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5008:8080"
      - "5058:8081"

  analytics-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./src/Services/Analytics/Analytics.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5009:8080"
      - "5059:8081"
