apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: pubs-microservices
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong@Passw0rd"
  ConnectionString: "Server=sqlserver-service;Database=PubsDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: pubs-microservices
type: Opaque
stringData:
  RABBITMQ_DEFAULT_PASS: "guest"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
