apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-api
  namespace: pubs-microservices
  labels:
    app: authors-api
    service: authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authors-api
  template:
    metadata:
      labels:
        app: authors-api
        service: authors
    spec:
      containers:
      - name: authors-api
        image: pubs/authors-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: ConnectionString
        - name: MessageBroker__Host
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQ__Host
        - name: MessageBroker__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQ__Username
        - name: MessageBroker__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQ__Password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: authors-api
  namespace: pubs-microservices
  labels:
    app: authors-api
    service: authors
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: authors-api
